import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/functional/header";
import { Locale } from "@/types";
import Footer from "@/components/functional/footer";
import Providers from "@/utils/providers";
import AutoScrollToTop from "@/components/functional/auto-scroll-fix";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ lang: string }>;
}>) {
  const { lang } = await params;
  return (
    <html lang={lang}>
      <body className={`${geistSans.variable} ${geistMono.variable} bg-white antialiased `}>
        <Providers>
          <>
            <AutoScrollToTop />
            <Header locale={lang as Locale} />
            {children}
            <Footer locale={lang as Locale} />
          </>
        </Providers>
      </body>
    </html>
  );
}
